#include <string>
#include "DofForm.h"

using namespace magnumfe;

DofForm::DofForm(uint rank, uint num_coefficients)
  : _function_spaces(rank + num_coefficients), _coefficients(num_coefficients), _rank(rank)
{
  // Do nothing
}

DofForm::DofForm(std::vector<boost::shared_ptr<const dolfin::FunctionSpace> > function_spaces,
                 std::vector<boost::shared_ptr<const dolfin::GenericFunction> > coefficients)
  : _function_spaces(function_spaces), _coefficients(coefficients),
    _rank(function_spaces.size())
{
  // Do nothing
}
//-----------------------------------------------------------------------------
DofForm::~DofForm()
{
  // Do nothing
}
//-----------------------------------------------------------------------------
uint DofForm::rank() const
{
  return _rank;
}
//-----------------------------------------------------------------------------
uint DofForm::num_coefficients() const
{
  return _coefficients.size();
}
//-----------------------------------------------------------------------------
boost::shared_ptr<const dolfin::FunctionSpace> DofForm::function_space(uint i) const
{
  dolfin_assert(i < _function_spaces.size());
  return _function_spaces[i];
}
//-----------------------------------------------------------------------------
std::vector<boost::shared_ptr<const dolfin::FunctionSpace> > DofForm::function_spaces() const
{
  return _function_spaces;
}
//-----------------------------------------------------------------------------
void DofForm::set_coefficient(uint i,
                           boost::shared_ptr<const dolfin::GenericFunction> coefficient)
{
  dolfin_assert(i < _coefficients.size());
  _coefficients[i] = coefficient;
}
//-----------------------------------------------------------------------------
void DofForm::set_coefficient(std::string name,
                           boost::shared_ptr<const dolfin::GenericFunction> coefficient)
{
  set_coefficient(coefficient_number(name), coefficient);
}
//-----------------------------------------------------------------------------
void DofForm::set_coefficients(std::map<std::string, boost::shared_ptr<const dolfin::GenericFunction> > coefficients)
{
  std::map<std::string, boost::shared_ptr<const dolfin::GenericFunction> >::iterator it;
  for (it = coefficients.begin(); it != coefficients.end(); ++it)
    set_coefficient(it->first, it->second);
}
//-----------------------------------------------------------------------------
boost::shared_ptr<const dolfin::GenericFunction> DofForm::coefficient(uint i) const
{
  dolfin_assert(i < _coefficients.size());
  return _coefficients[i];
}
//-----------------------------------------------------------------------------
boost::shared_ptr<const dolfin::GenericFunction> DofForm::coefficient(std::string name) const
{
  return coefficient(coefficient_number(name));
}
//-----------------------------------------------------------------------------
std::vector<boost::shared_ptr<const dolfin::GenericFunction> > DofForm::coefficients() const
{
  return _coefficients;
}
//-----------------------------------------------------------------------------
dolfin::uint DofForm::coefficient_number(const std::string & name) const
{
  // NOT IMPLEMENTED
  // TODO: Dissect name, assuming "wi", and return i.
  return 0;
}
//-----------------------------------------------------------------------------
std::string DofForm::coefficient_name(uint i) const
{
  // Create name like "w0", overloaded by Form subclasses generated by form compilers
  std::ostringstream name;
  name << "w" << i;
  return name.str();
}

boost::shared_ptr<const dolfin::Mesh> DofForm::mesh() const
{
  return function_space(0)->mesh();
}
